<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CareerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $careers = [
            ['career_code' => 'Q343', 'name' => 'Pedagogia Musical', 'operating_area_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'No existe programa en grado', 'name' => 'Ciencias De La Educacion', 'operating_area_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q344', 'name' => 'Pedagogia De Las Artes Y Humanidades', 'operating_area_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q340', 'name' => 'Educacion Inicial', 'operating_area_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q353', 'name' => 'Lingüistica', 'operating_area_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q352', 'name' => 'Comunicacion', 'operating_area_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q354', 'name' => 'Lenguas Aplicadas A Los Estudios Globales ', 'operating_area_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q355', 'name' => 'Literatura', 'operating_area_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q087', 'name' => 'Multilingüe En Negocios Y Relaciones Internacionales ', 'operating_area_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'NV14', 'name' => 'Educacion Basica Virtual', 'operating_area_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'NV15', 'name' => 'Educacion Inicial Virtual', 'operating_area_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q339', 'name' => 'Bioingenieria', 'operating_area_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q334', 'name' => 'Biologia', 'operating_area_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q169', 'name' => 'Biologia', 'operating_area_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q189', 'name' => 'Biologia', 'operating_area_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q337', 'name' => 'Ingenieria En Ciencias De Datos ', 'operating_area_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q338', 'name' => 'Licenciatura En Ciencias Biomedicas ', 'operating_area_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q032', 'name' => 'Ciencias Quimicas', 'operating_area_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q335', 'name' => 'Microbiologia', 'operating_area_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q336', 'name' => 'Quimica ', 'operating_area_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q369', 'name' => 'Filosofia', 'operating_area_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q370', 'name' => 'Teologia', 'operating_area_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q364', 'name' => 'Derecho', 'operating_area_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q387', 'name' => 'Derecho', 'operating_area_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q345', 'name' => 'Antropologia', 'operating_area_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q347', 'name' => 'Historia', 'operating_area_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'No existe programa', 'name' => 'Ingenieria En Geografia', 'operating_area_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q200', 'name' => 'Hospitalidad Y Hoteleria', 'operating_area_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q346', 'name' => 'Arqueologia', 'operating_area_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q348', 'name' => 'Ciencias Politicas', 'operating_area_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q217', 'name' => 'Gestion Hotelera', 'operating_area_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q144', 'name' => 'Gestion Social', 'operating_area_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q349', 'name' => 'Gestion Social Y Desarrollo', 'operating_area_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q351', 'name' => 'Sociologia', 'operating_area_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q203', 'name' => 'Turismo', 'operating_area_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q350', 'name' => 'Relaciones Internacionales', 'operating_area_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q356', 'name' => 'Economia', 'operating_area_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'No existe programa', 'name' => 'Ingenieria Comercial', 'operating_area_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q329', 'name' => 'Contabilidad Y Auditoria', 'operating_area_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q328', 'name' => 'Administracion De Empresas  ', 'operating_area_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q330', 'name' => 'Finanzas', 'operating_area_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q331', 'name' => 'Marketing', 'operating_area_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q332', 'name' => 'Negocios Internacionales  ', 'operating_area_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q372', 'name' => 'Administracion En Turismo Y Hospitalidad', 'operating_area_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'NV11', 'name' => 'Administracion De Empresas Virtual', 'operating_area_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'NV13', 'name' => 'Economia Virtual', 'operating_area_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'NV12', 'name' => 'Contabilidad Y Auditoria Virtual', 'operating_area_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q323', 'name' => 'Arquitectura', 'operating_area_id' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q324', 'name' => 'Artes Visuales', 'operating_area_id' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'No existe programa', 'name' => 'Diseño Profesional', 'operating_area_id' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q325', 'name' => 'Diseño De Productos ', 'operating_area_id' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q326', 'name' => 'Diseño Grafico', 'operating_area_id' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'NV01', 'name' => 'Ciberseguridad Y Gestion De Las Tecnologias De La Informacion Virtual', 'operating_area_id' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q395', 'name' => 'Ingenieria En Diseño Industrial', 'operating_area_id' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q360', 'name' => 'Ingenieria Civil', 'operating_area_id' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q096', 'name' => 'Ingenieria De Sistemas Y Computacion', 'operating_area_id' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q361', 'name' => 'Ingenieria En Sistemas De Informacion', 'operating_area_id' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q212', 'name' => 'Ingenieria En Tecnologias De La Informacion', 'operating_area_id' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q359', 'name' => 'Fisioterapia', 'operating_area_id' => 71, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q092', 'name' => 'Nutricion Humana', 'operating_area_id' => 71, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q358', 'name' => 'Nutricion Y Dietetica', 'operating_area_id' => 71, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q093', 'name' => 'Terapia Fisica', 'operating_area_id' => 71, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q365', 'name' => 'Medicina', 'operating_area_id' => 74, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q381', 'name' => 'Odontologia', 'operating_area_id' => 74, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q386', 'name' => 'Odontologia', 'operating_area_id' => 74, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q366', 'name' => 'Laboratorio Clinico', 'operating_area_id' => 72, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q108', 'name' => 'Bioquimica Clinica', 'operating_area_id' => 72, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q357', 'name' => 'Enfermeria', 'operating_area_id' => 72, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q382', 'name' => 'Medicina Veterinaria', 'operating_area_id' => 72, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q367', 'name' => 'Psicologia Clinica', 'operating_area_id' => 73, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q374', 'name' => 'Psicologia Educativa', 'operating_area_id' => 73, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q375', 'name' => 'Psicologia Organizacional', 'operating_area_id' => 73, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q371', 'name' => 'Psicologia General', 'operating_area_id' => 73, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ18', 'name' => 'Fotografia Equivalente A Tecnologia Superior', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ03', 'name' => 'Fotografia Equivalente A Tecnologia Superior', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ20', 'name' => 'Tecnologia Superior En Accion Pastoral', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ01', 'name' => 'Tecnologia Superior En Administracion De Las Organizaciones De La Economia Popular Y Solidaria', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ07', 'name' => 'Tecnologia Superior En Atencion Integral A Adultos Mayores', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ08', 'name' => 'Tecnologia Superior En Construccion', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ23', 'name' => 'Tecnologia Superior En Construccion', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ02', 'name' => 'Tecnologia Superior En Desarrollo De Software', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ16', 'name' => 'Tecnologia Superior En Desarrollo De Software', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ04', 'name' => 'Tecnologia Superior En Enfermeria', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ22', 'name' => 'Tecnologia Superior En Enfermeria', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ05', 'name' => 'Tecnologia Superior En Gestion Culinaria', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ11', 'name' => 'Tecnologia Superior En Negociacion Y Ventas', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ10', 'name' => 'Tecnologia Superior Universitaria En Interpretacion De Legua De Señas', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ19', 'name' => 'Tecnologia Superior Universitaria En Interpretacion De Legua De Señas', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ17', 'name' => 'Teonologia Superior En Gestion De Talento Humano. ', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'TQ12', 'name' => 'Teonologia Superior En Gestion De Talento Humano. ', 'operating_area_id' => 81, 'created_at' => now(), 'updated_at' => now()],
            ['career_code' => 'Q269', 'name' => 'Ingenieria Integral', 'operating_area_id' => 91, 'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('careers')->insert($careers);
    }
}
